title: Book
description: Programmer & Traveler.
url: http://kkninjae.com
avatar: /book/assets/img/avatar.jpg
favicon: /book/assets/img/favicon.ico
google_analytics: UA-66887095-1
disqus_shortname: keshaun

about:
  - paragraph: ?link?, a simple Jekyll theme. Built by ?link?
    text_align: center
    links:
      - name: Book
        url: https://github.com/keshaun/book
        external: true
      - name: Lang Liu
        url: http://kkninjae.com/about/
        external: false

    
